# Generated by Django 3.0.6 on 2020-05-30 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potName', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
                ('potType', models.CharField(choices=[('Tower', 'Vertical Tower'), ('Reservoir', 'Flat Bed Reservoir'), ('Pipe', 'Single Line Pipe')], default='Tower', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantName', models.CharField(max_length=50)),
                ('plantedDate', models.DateTimeField(auto_now_add=True)),
                ('Pot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='potRegister.Pot')),
            ],
        ),
    ]
