# Generated by Django 3.0.6 on 2020-05-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
